### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by dciccale** [SliceMeNice/vagrant-docker-shopware#1]
Hi, I'm trying to run the installation of shopware but on the Database configuration step this error is shown "SQLSTATE[HY000] [2002] No such file or directory"

![screen shot 2016-09-20 at 12 21 50](https://cloud.githubusercontent.com/assets/539546/18666575/dc07c1a8-7f2c-11e6-8325-b2ca09dd6629.png)

here are the running containers

![screen shot 2016-09-20 at 12 19 28](https://cloud.githubusercontent.com/assets/539546/18666579/e10beaa8-7f2c-11e6-9b58-cd3e13d4c8ed.png)

I'm using Docker for Mac 1.12.1

**Comment by stefanullinger** [comment]
Hi Denis,

sorry – this setup is quite old – I think vagrant is not necessary anymore.

But regarding your error: Can you try to set the database host to "db" instead of "localhost"? The reason is, that the containers are linked to each other and you have to reference the database container via it's name.

**Comment by dciccale** [comment]
OK, using "db" it worked! thanks.

I'm not using vagrant, just docker.
